### ISSUE TITLE
constant rain is an integer, change to number with decimals

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-api-qgis-client#180] opened 2021-09-17 07:30 UTC
I want to calculate 27.85 mm/h, this is not possible:
![image](https://user-images.githubusercontent.com/1453159/133742678-d4ef0d28-ac3a-4a18-b6fe-f0f31af0c706.png)

**Comment by leendertvanwolfswinkel** [comment] 2022-03-07 12:47
duplicate of #347

**Closed by leendertvanwolfswinkel** 2022-03-07 12:47 UTC
Labels: bug, quick win
